### PR TITLE
Slight update: Adds a flair of coefficients and adds templates

### PR DESCRIPTION
**Pull request by FxllenCode**
makes it more pog!

Jokes aside, solves:

https://github.com/ElliottLMz/devforumplus/issues/2

Also adds a few templates.

### CODE REVIEW

**Comment by FxllenCode** [comment]
Oops-- noticed something, don't merge yet.

**Comment by Noted-Jrelvas** [comment]
yes. x2

**Review by posatta — CHANGES_REQUESTED** [review]
There's a few typos. !!CALLOUT has "expirence", "disupute", and "againt". "bruh" is also Ondrashek06's flair, in case you want to have a comment for that

**Comment by FxllenCode** [comment]
@posatta oops good point, will also fix that.

**Pull request merged**
