### PR TITLE
lua template

### PR DESCRIPTION
**Pull request by Ewanophobia**
stops people from saying LUA or L.U.A

### CODE REVIEW

**Comment by ElliottLMz** [comment]
needs community review before i merge

**Review by posatta — APPROVED** [review]
Looks good

**Comment by zapacni** [comment]
I recommend linking to https://www.lua.org/about.html and quoting this bit:

image

**Comment by Ewanophobia** [comment]
@zapacni done

i just did the link because i don't think there's a need to add anything else to the message

**Review by ElliottLMz — APPROVED** [review]

**Pull request merged**
